#!/bin/bash

# see https://github.com/noanabeshima/wikipedia-downloader
# warning ; this is SLOW

git clone https://github.com/noanabeshima/wikipedia-downloader.git
cd wikipedia-downloader
conda create --name wikipedia

conda init
exec bash

conda activate wikipedia
bash install_requirements.sh
python main.py
