version: "3"

services:
  basemlpython:
    image: basemlpython
    build: .
    restart: always
    #ports:
    #  - "3001:3001"
    volumes:
      - data:/data
    depends_on:
      - cache

  cache:
    image: redis:6.2-alpine
    restart: always
    #ports:
    #  - '6379:6379'
    volumes:
      - ./cache:/data

